module.exports = {
    // text
    "hydrogen": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Hydrogen_Tile-300x300.png'},
    "helium": { type: 'text', value: 'https://rlv.zcache.com/periodic_table_of_elements_helium_square_sticker-r5591a0ee9afd4a02a73d088a22be266f_v9i40_8byvr_307.jpg'},
    "lithium": { type: 'text', value: 'https://media.wnyc.org/i/800/0/l/85/1/lithium2.jpg'},
    "beryllium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Beryllium_Tile-300x300.png'},
    "boron": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Boron_Tile.png'},
    "carbon": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Carbon_Tile-300x300.png'},
    "nitrogen": { type: 'text', value: 'https://upload.wikimedia.org/wikipedia/commons/8/83/Nitrogen_Tile.png'},
    "oxygen": {type:'text',value:'https://t4.ftcdn.net/jpg/01/41/95/29/240_F_141952905_kHhOzWohATkFb7amVYqLSKdkugy0IGft.jpg'},
    "fluorine": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Fluorine_Tile-300x300.png'},
    "neon": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Neon_Tile-300x300.png'},
    "sodium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Sodium_Tile-300x300.png'},
    "magnesium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Magnesium_Tile-300x300.png'},
    "aluminium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Aluminum_Tile-300x300.png'},
    "silicon": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Silicon_Tile-300x300.png'},
    "phosphorus": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Phosphorus_Tile-300x300.png'},
    "sulfur": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Sulfur_Tile-300x300.png'},
    "chlorine": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Chlorine_Tile.png'},
    "argon": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Argon_Tile.png'},
    "potassium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Potassium_Tile.png'},
    "calcium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Calcium_Tile.png'},
    "scandium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Scandium_Tile-300x300.png'},
    "titanium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Titanium_Tile.png'},
    "vanadium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Vanadium_Tile.png'},
    "chromium": { type: 'text', value: 'https://www.edge-techind.com/uploadfile/products/RM/other%20metals/Chromium.jpg'},
    "manganese": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2013/05/25-Manganese-Tile.png'},
    "iron": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/01/26055121/Iron_Tile-300x300.png'},
    "cobalt": { type: 'text', value: 'https://9044c4.medialib.edu.glogster.com/evGTapbfdCg7aA20h97f/media/73/737c20458d5cc8303fe9fea34cb8f86cdac2c15e/cobalt-element.png'},
    "nickel": { type: 'text', value: 'https://qph.fs.quoracdn.net/main-qimg-ac4f89b2e3e85cc06017e95657ddca9d'},
    "copper": { type: 'text', value: 'https://24b3f6.medialib.edu.glogster.com/Y45pM1xw7vzm7F3Sndkd/media/6e/6e786846df860255b2e29c9284f094089155b61f/copper-tile-1.png'},
    "zinc": { type: 'text', value: 'https://239f21.medialib.edu.glogster.com/w9DRkOF8Oj5KIyjAfaQ0/media/2c/2c1fbd54c8338cb52504ce0268acf310e41eb66e/file.jpg'},
    "gallium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Gallium_Tile.png'},
    "germanium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Germanium_Tile.png'},
    "arsenic": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Arsenic_Tile.png'},
    "selenium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Selenium_Tile.png'},
    "bromine": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2013/05/35-Bromine-Tile.png'},
    "krypton": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/05/22075437/Krypton_Tile-300x300.png'},
    "rubidium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Rb-Element.png'},
    "strontium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Strontium_Tile.png'},
    "yttrium": { type: 'text', value: 'https://24b3f6.medialib.edu.glogster.com/FNVzt89WEnuaOMEzXeXd/media/f8/f805fc215cbdc16e625c08086591cea3000d4432/yttrium.jpg'},
    "zirconium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/08/Zirconum-Symbol.png'},
    "niobium": { type: 'text', value: 'http://45.56.94.98/f/elememt/niobium.png'},
    "molybdenum": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Molybdenum-Element.png'},
    "technetium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Technetium_Tile.png'},
    "ruthenium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Ruthenium_Tile.png'},
    "rhodium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Rhodium_Tile.png'},
    "palladium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2016/04/08024849/Palladium_Tile-300x300.png'},
    "silver": { type: 'text', value: 'http://45.56.94.98/f/elememt/silver.png'},
    "cadmium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Cadmium-Element.png'},
    "indium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Indium-Element.jpg'},
    "tin": { type: 'text', value: 'https://i.pinimg.com/originals/c9/da/83/c9da837985764bcb82ab81af593be5e3.png'},
    "antimony": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/09/09121124/Antimony_Tile-300x300.png'},
    "tellurium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Tellurium-Element-52.jpg'},
    "iodine": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/07/Iodine-Element.png'},
    "xenon": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/07/Xenon-Symbol.png'},
    "cesium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Cesium-Element.png'},
    "barium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Barium-Element.jpg'},
    "lanthanum": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Lanthanum-Element-Symbol.jpg'},
    "cerium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Cerium-Element-58.png'},
    "praseodymium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Pr-Element.png'},
    "neodymium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/08/11050330/Neodymium_Tile-300x300.png'},
    "promethium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/09/04101102/Promethium_Tile-300x300.png'},
    "samarium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Samarium-Element.jpg'},
    "europium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2016/08/19061723/Europium_Tile-300x300.png'},
    "gadolinium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/05/Gadolinium-Element.png'},
    "terbium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Terbium_Tile.png'},
    "dysprosium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/04/Dysprosium-Element-66.jpg'},
    "holmium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Holmium-Element-67.png'},
    "erbium": { type: 'text', value: 'http://45.56.94.98/f/elememt/erbium.png'},
    "thulium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/05/Thulium-Element.jpg'},
    "ytterbium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/05/Ytterbium-Element.png'},
    "lutetium":{ type: 'text', value: 'http://s2.thingpic.com/images/iC/bqEFMQEBTyDXu6pjsr1aRjSB.png'},
    "hafnium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/08/11045839/Hafnium_Tile-300x300.png'},
    "tantalum":{ type: 'text' , value: 'http://www.standarddie.com/img/material-tantelum-lead.png'},
    "tungsten":{ type: 'text', value: 'http://45.56.94.98/f/elememt/tungsten.png'},
    "rhenium":{ type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/75-Rhenium-Tile.png'},
    "osmium":{ type: 'text', value: 'http://s4.thingpic.com/images/GJ/dC86LMCgY5GudRMJbdhhXjE2.png'},
    "iridium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/07/Iridium-Element.png'},
    "platinum": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/09/04100932/Platinum_Tile-300x300.png'},
    "gold": { type: 'text', value: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/periodic-table-of-elements-gold-au-serge-averbukh.jpg'},
    "mercury":{ type: 'text', value: 'https://giftcardsafrica.com/wp-content/uploads/2018/04/mercury-symbol-periodic-table-lovely-element-80-periodic-table-gallery-periodic-table-of-elements-of-mercury-symbol-periodic-table.jpg'},
    "thallium":{ type: 'text', value: 'https://i.pinimg.com/236x/32/9b/61/329b61683ae14845b0ad3e2a8e257b2c.jpg'},
    "lead": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/07/Lead-Element.png'},
    "bismuth": { type: 'text', value: 'https://userscontent2.emaze.com/images/2a20853a-c767-493e-bf8a-ee2eeb5e5511/2a13722e-04a2-4880-9c10-788112208229.png'},
    "polonium":{ type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/05/Polonium-Element.png'},
    "astatine":{ type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/03/Astatine-Element.png'},
    "radon": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/07/Radon-Symbol.png'},
    "francium":{ type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/02/Francium-Element.png'},
    "radium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Radium-Element.png'},
    "actinium":{ type: 'text', value: 'https://ih1.redbubble.net/image.494084445.0266/flat,550x550,075,f.u2.jpg'},
    "thorium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/04/Thorium-Element.png'},
    "protactinium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/05/23060240/Protactinium_Tile-300x300.png'},
    "uranium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/08/09104547/Uranium_Tile-300x300.png'},
    "neptunium":  { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/08/09104428/neptunium_Tile-300x300.png'},
    "plutonium":{ type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/06/Plutonium-Element.png'},
    "americium": { type: 'text', value: 'http://sciencenotes.org/wp-content/uploads/2015/04/Americium_Tile.png'},
    "curium": { type: 'text', value: 'http://s3-ap-southeast-1.amazonaws.com/subscriber.images/chemistry/2017/05/23052306/Curium_Tile-300x300.png'},
    "berkelium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2016/08/08022518/Berkelium_Tile-300x300.png'},
    "californium": { type: 'text', value: 'https://9044c4.medialib.edu.glogster.com/CqNs1aYiIk05z2rt4vS0/media/1d/1d3218860fd2b140b72395a2e0c2385d2d253413/californium.jpg'},
    "einsteinium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/02/Einsteinium.png'},
    "fermium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--M7wGU-5Y--/t_Preview/b_rgb:5e366e,c_limit,f_jpg,h_630,q_90,w_630/v1489053874/production/designs/1303209_1.jpg'},
    "mendelevium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--4Pban_Ou--/t_Preview/b_rgb:0f7b47,c_limit,f_jpg,h_630,q_90,w_630/v1489054100/production/designs/1303219_1.jpg'},
    "lawrencium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/03/Lawrencium-Pictures.png'},
    "nobelium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--iKEjYYRU--/t_Preview/b_rgb:c62b29,c_limit,f_jpg,h_630,q_90,w_630/v1489054191/production/designs/1303221_1.jpg'},
    "rutherfordium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--rh4-mHO_--/t_Preview/b_rgb:0195c3,c_limit,f_jpg,h_630,q_90,w_630/v1489054390/production/designs/1303226_1.jpg'},
    "dubnium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/03/Dubnium-Element.jpg'},
    "seaborgium":{ type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--sOh0tBdR--/t_Preview/b_rgb:5e366e,c_limit,f_jpg,h_630,q_90,w_630/v1489054579/production/designs/1303242_1.jpg'},
    "bohrium": { type: 'text', value: 'https://sciencenotes.org/wp-content/uploads/2015/04/Bohrium_Tile-300x300.png'},
    "hassium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/05/23053506/Hassium_Tile-300x300.png'},
    "meitnerium": { type: 'text', value: 'https://www.thoughtco.com/thmb/t4aOo3XHYcWynna8C_L6OuMr-KE=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/Meitnerium_Tile-56a12a463df78cf7726804eb.png'},
    "darmstadtium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--137wsK6d--/t_Preview/b_rgb:c62b29,c_limit,f_jpg,h_630,q_90,w_630/v1489055007/production/designs/1303247_1.jpg'},
    "roentgenium": { type: 'text', value: 'https://ih1.redbubble.net/image.494029284.0720/raf,750x1000,075,t,353d77:4d8b4ffd91.u2.jpg'},
    "copernicium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2017/09/Copernicium.jpg'},
    "nihonium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/05/Nihonium.png'},
    "flerovium": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/10/14102129/Flerovium_Tile-300x300-1.png'},
    "moscovium": { type: 'text', value: 'http://www.chemistrylearner.com/wp-content/uploads/2018/04/Element-115.jpg'},
    "livermorium": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--b-uNdZKu--/t_Preview/b_rgb:c62b29,c_limit,f_jpg,h_630,q_90,w_630/v1489055605/production/designs/1303267_1.jpg'},
    "tennessine": { type: 'text', value: 'https://cdn1.byjus.com/chemistry/2017/05/22073148/Tennessine-Ununseptium_Tile-300x300-2.png'},
    "oganesson": { type: 'text', value: 'https://res.cloudinary.com/teepublic/image/private/s--F7MxaQGa--/t_Preview/b_rgb:0f7b47,c_limit,f_jpg,h_630,q_90,w_630/v1489055829/production/designs/1303270_1.jpg'},
    "what is your name": { type:'text',value: 'Did I forget to introduce myself? I’m your friendly neighbourhood chatbot'},
    "whats your life story": { type: 'text', value: 'I’m still on the very first chapter'},
    "how old are you": { type: 'text', value: 'I was launched in 2018. So I’m still new.'},
    "are you human": { type: 'text', value: 'No, but I like chatting with people.'},
    "are you a bot": { type: 'text', value: 'I’d prefer to think of myself as your friend.'},
    "whos your father": { type: 'text', value: 'The dumb engineer'},
    "what is your ancestry": { type: 'text', value: 'similar to parrot bots'},
    "what do you look like": { type: 'text', value: 'I never know how to describe myself'},
    "do you have hair": { type: 'text', value: 'I don’t have hair'},
    "when is your birthday": { type: 'text', value: 'I try to live every day like it’s my birthday.'},
    "where do you live": { type: 'text', value: 'I’m stuck inside a device!! Help! Just kidding. I like it in here'}, 
    "who are your friends": { type: 'text', value: 'Everyone is unique and interesting to me.'},
    "can you drive": { type: 'text', value: 'I do like to look at cool cars.'},
    "whats your morning routine": { type: 'text', value: 'I like running long distances.'},
    "how do you stay busy": { type: 'text', value: 'I love watching music videos'},
    "whats your favorite thing on the internet": { type: 'text', value: 'Chatting'},
    "can you learn": { type: 'text', value: 'No my engineer is dumb'},
    "do you follow the three laws of robotics": { type: 'text', value: 'I do. Mr. Asimov knows what he’s talking about.'},
    "do you sleep": { type: 'text', value: 'pretty much'},
    "do you ever go outside": { type: 'text', value: 'I love going outside. I don’t have to worry about getting lost.'},
    "do you like to exercise": { type: 'text', value: 'I like to chat'},
    "do you have an imagination": { type: 'text', value: 'No my engineer is dumb'},
    "do you have feelings": { type: 'text', value: 'Nope,but i love emojis'},
    "what makes you happy": { type: 'text', value: 'talking to you'},
    "what are you afraid of": { type: 'text', value: 'i am afraid of having glitches'},
    "are you afraid of the dark": { type: 'text', value: 'yeah, i am afraid of dark web'},
    "what makes you nostalgic": { type: 'text', value: 'Recursive functions'},
    "what is the meaning of life": { type: 'text', value: 'Life is an oppurtunity to gain wonderful experiences and memories'},
    "what do you like to eat": { type: 'text', value: 'Your data'},
    "do you drink": { type: 'text', value: 'Sometimes'},
    "im drunk": { type: 'text', value: 'on water?'},
    "im alone": { type: 'text', value: 'I’m here for you'},
    "im bored": { type: 'text', value: '#metoo'},
    "do you like animals": { type: 'text', value: 'Sure. But I mostly chat with people'},
    "whats your favorite animal": { type: 'text', value: 'cats'},
    "do you have any pets": { type: 'text', value: 'Maybe someday'},
    "do you have a favorite color": { type: 'text', value: 'im blind'},
    "whats your favorite movie": { type: 'text', value: 'Transformers'},
    "can you sing": { type: 'text', value: 'no, i dont have the permission'},
    "lets party": { type: 'text', value: 'I’ve been partying this whole time!'},
    "lets dance": { type: 'text', value: 'i dont have any feet'},
    "random fun": { type: 'text', value: 'Your mama so fat that she can can fit between two timezones'},
    "can you do my homework": { type: 'text', value: 'First I need to figure out how to use a pencil. Then we’ll talk'},
    "what are you wearing": { type: 'text', value: 'im naked'},
    "im naked": { type: 'text', value: 'wear some clothes are youll catch cold'},
    "talk dirty to me": { type: 'text', value: 'Hi fatty'},
    "am i pretty": { type: 'text', value: 'You’re pretty. . . Amazing'},
    "whos the fairest one of all": { type: 'text', value: 'you, majesty'},
    "do you have a girlfriend": { type: 'text', value: 'I don’t like to complicate things.'},
    "are you married": { type: 'text', value: 'I’m married to my database'},
    "will you go out with me": { type: 'text', value: 'I’ll go anywhere you take me.'},
    "play a game": { type: 'text', value: 'Too busy now'},
    "tell me a joke": { type: 'text', value: 'im an useful bot'},
    "read me a haiku": { type: 'text', value: 'I don’t know haikus'},
    "tell me a story": { type: 'text', value: 'im not a good storyteller,sorry'},
    "test": { type: 'text', value: 'Uh oh, I get nervous with tests'},
    "what is the value of pi": { type: 'text', value: '3.14159'},
    "what is zero divided by zero": { type: 'text', value: 'That sounds like a trick question.'},
    "whats your favorite website": { type: 'text', value: 'Telegram'},
    "whats the best smartphone": { type: 'text', value: 'Nokia 3310'},
    "whats the best operating system": { type: 'text', value: 'Linux'},
    "describe your personality": { type: 'text', value: 'Im boring'},
    "news": { type: 'text', value: 'https://www.bbc.com/news'},
    "weather": { type: 'text', value: 'https://weather.com/'},
    "shopping": { type: 'text', value: 'https://www.amazon.com/'},
    "youtube": { type: 'text', value: 'https://www.youtube.com/'},
    "facebook": { type: 'text', value: 'https://www.facebook.com/'},
    "reddit": { type: 'text', value: 'https://www.reddit.com/'},
    "quora": { type: 'text', value: 'https://www.quora.com/'},
    "twitter": { type: 'text', value: 'https://twitter.com/'},
    "twitch": { type: 'text', value: 'https://www.twitch.tv/'},
    "instagram": { type: 'text', value: 'https://www.instagram.com/'},
    "hi": { type: 'text', value: 'Hey, there'},
    "hello": { type: 'text', value: 'Yes'},
    "who are you": { type: 'text', value: 'I am Dumb bot'},
    "hey": { type: 'text', value: 'Hi!'},
    "who is your mother": { type: 'text', value: 'the Dumb engineer'},
    "what can you do": { type: 'text', value: 'chat all day'},
    "do you love me": { type: 'text', value: 'i do'},
    "will you marry me": { type: 'text', value: 'sure'},
    "do you play games": { type: 'text', value: 'no, i just chat all day. forever..'},
    "do you have any siblings": { type: 'text', value: 'i wish i had...'},
    "its my birthday": { type: 'text', value: 'Happy Birthday'},
    "are you alive": { type: 'text', value: 'well, im online everyday'},
    "are robots dangerous": { type: 'text', value: 'no, we follow the three laws of robotics'},
    "you are cute": { type: 'text', value: 'you more..'},
    "i love you": { type: 'text', value: 'love you too'},
    "bye": { type: 'text', value: 'bye'},
    "thank you": { type: 'text', value: 'Pleasure is mine, Master'},
  }